apiVersion: v1
kind: Pod
metadata:
  name: conversao-temperatura
spec:
  containers:
    - name: conversao-temperatura
      image: sicemal/conversao-temperatura:v1
      ports:
        - containerPort: 8080

# kubectl apply -f pod.xaml