# docker-compose.yaml
version: "3"

networks:
  app-network:
    driver: bridge

services:
  web:
    image: sicemal/conversao-distancia:v1
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 5000:5000
    networks:
      - app-network
