version: "3"

networks:
  compose-network:
    driver: bridge

volumes:
  db:

services:
  db:
    image: mariadb:10.11.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - compose-network

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    ports:
      - 8081:80
    environment:
      MYSQL_USERNAME: "user"
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - compose-network
    depends_on:
      - db
