version: '3'

networks: 
    compose-network:
      driver: bridge  

volumes:
  db:

services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - compose-network      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    ports:
      - 8081:80
    environment:
      MYSQL_USERNAME: 'user'
      MYSQL_ROOT_PASSWORD: 'password'     
    networks:
      - compose-network      
    depends_on:
      - db

