version: "3"

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  db:

services:
  teste-postgres-compose:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    container_name: admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "silvio@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "16543:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network
